language: php

php:
  - 7.1
  - 7.2
  - nightly

cache:
  directories:
    - $HOME/.composer/cache

env:
  matrix:
    - PREFER_LOWEST="--prefer-lowest"
    - PREFER_LOWEST=""

matrix:
  allow_failures:
    - php: nightly


install:
  - composer update $PREFER_LOWEST

before_script:
  - if [ $TRAVIS_PHP_VERSION = '7.2' ]; then PHPUNIT_FLAGS="--coverage-clover coverage.xml"; fi

script:
  - phpunit $PHPUNIT_FLAGS

after_script:
  - if [ $TRAVIS_PHP_VERSION = '7.2' ]; then wget https://scrutinizer-ci.com/ocular.phar && php ocular.phar code-coverage:upload --format=php-clover coverage.xml; fi
