language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm

env:
  matrix:
    - PREFER_LOWEST="--prefer-lowest"
    - PREFER_LOWEST=""

matrix:
  fast_finish: true
  allow_failures:
    - php: 7.0

install:
  - composer update --prefer-source $PREFER_LOWEST

script:
  - phpunit
